name: Github actions demo
on: 
  pull_request:
    types: close
jobs:
  Demo-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Yay!"
      - name: Do something..
        run: echo "${{ github.event.pull_request.labels.*.name }}"
        run: echo "${{ github.event.pull_request.head.ref }}"