name: Github actions demo
on:
  push:
    branches: [main]
jobs:
  Demo-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - uses: MaetDol/CodeReview-github-action-test/build-all-sub-directory@v1
      
      - name: Git configuring
      - run: |
          git config user.name 'MaetDol'
          git config user.email 'rndka9@gmail.com'
          
      - name: Deploy
        run: |
          git add --all
          git commit -m 'Deploy build output by Github workflow'
          git checkout gh-pages
          git merge main
          git push origin gh-pages
