name: Github actions demo
on:
  push:
    branches: [main]
jobs:
  Demo-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - uses: Awesome-Tomato/build-all-sub-directory/get-build-target-fullpaths@v1
        with:
          workspace: ${{ env.GIHUB_WORKSPACE }}
