name: Github actions demo
on:
  push:
    branchs: [main]
jobs:
  Demo-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Yay!"
      - run: echo "${{ github.event.pull_request.labels.*.name }}"
      - run: echo "${{ github.event.pull_request.head.ref }}"
